version: "3.9"
   
services:
  www:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: backend
    user: ${UID}:${UID}
    
    volumes:
      - ./backend:/app
      # custom adjustments to php.ini
      # i. e. "xdebug.remote_host" to debug the dockerized app
      - ./docker/php:/usr/local/etc/php/local.conf.d/
    environment:
      # add our custom config files for the php to scan
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
    command: "php artisan serve --host=0.0.0.0 --port=8080"
  
  frontend:
    build:
      context: frontend
    user: ${UID}:${UID}
    volumes:
    - ./frontend:/app
    environment:
      NODE_ENV: development
    command: "yarn dev"








