version: "3.9"
   
services:
  www:
    image: nginx:alpine
    user: ${UID}:${GID}
    depends_on:
      - frontend
      - backend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  backend:
    build:
      context: backend
    user: ${UID}:${GID}
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      # custom adjustments to php.ini
      # i. e. "xdebug.remote_host" to debug the dockerized app
      - ./docker/php:/usr/local/etc/php/local.conf.d/
    environment:
      # add our custom config files for the php to scan
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
    command: "php artisan serve --host=0.0.0.0 --port=8080"
  
  frontend:
    build:
      context: frontend
    user: ${UID}:${GID}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    command: "yarn dev"
  
  db:
    image: mysql:latest
    user: ${UID}:${GID}
    volumes:
      - ./.docker_data/mysql:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: hootka
      MYSQL_USER: hootka
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
  
  redis:
    image: redis:alpine
    user: ${UID}:${GID}
    volumes:
      - ./.docker_data/redis:/data
      - ./docker/redis:/usr/local/etc/redis









